# Generated by Django 4.0.2 on 2022-02-05 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='member',
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='dept', max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=10)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='church.family')),
            ],
        ),
    ]
