# Generated by Django 4.0.2 on 2022-06-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_remove_event_week_event_end_date_event_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='item',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(),
        ),
    ]
