# Generated by Django 4.0.2 on 2022-02-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_calendaofevents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalendaOfEvents',
            new_name='Event',
        ),
    ]
