# Generated by Django 4.0.2 on 2022-03-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_rename_calendaofevents_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(upload_to=''),
        ),
    ]
