# Generated by Django 4.0.2 on 2022-09-04 12:37

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_alter_announcement_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=sorl.thumbnail.fields.ImageField(upload_to='images/'),
        ),
    ]
