# Generated by Django 4.0.2 on 2022-09-26 13:36

from django.db import migrations
import mmusdaweb.storages
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_alter_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=sorl.thumbnail.fields.ImageField(storage=mmusdaweb.storages.PublicMediaStorage, upload_to=''),
        ),
    ]
