# Generated by Django 4.1 on 2022-09-26 18:59

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_alter_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=sorl.thumbnail.fields.ImageField(upload_to=''),
        ),
    ]
