# Generated by Django 4.0.2 on 2022-09-28 06:21

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_alter_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=sorl.thumbnail.fields.ImageField(upload_to='images/'),
        ),
    ]
